#!/bin/bash

set -e
set -x

image_ns="$(echo ${IMAGE_NAME} | cut -d'/' -f1-2)"

archs="armv7 armhf aarch64 amd64 i386"
for arch in ${archs}; do
	docker push ${image_ns}/almond-hassio-addon-${arch}
done
